[project]
name = "kvoicewalk"
version = "0.1.0"
description = "A randomwalk through Kokoro latent space"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "kokoro>=0.9.4",
    "numpy>=2.2.6",
    "pip>=25.1.1",
    "resemblyzer>=0.1.4",
    "soundfile>=0.13.1",
    "torch>=2.7.0",
    "tqdm>=4.67.1",
    "faster-whisper>=1.1.1",
    "speechbrain>=1.0.3",
    "torchaudio>=2.7.0",
    "cma>=4.4.0",
]
